import "./globals.css";

import type { Metadata } from "next";
import clsx from "clsx";
import { nunito } from "@/app/ui/fonts";

import AppThemeProvider from "@/app/providers";
import TopNav from "@/app/ui/top-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          nunito.className,
          "bg-gray-100 dark:bg-gray-800 dark:text-white"
        )}
      >
        <AppThemeProvider>
          <TopNav />
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
